{% set name = "sober" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sober-{{ version }}.tar.gz
  sha256: e48778755914eadcbda21a390ca33aea6c1f2a36eedabd01eeecb99019017817

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.12.0,<4.0.0
    - pymoo >=0.6.1,<0.7.0
    - eppy-core >=0.5.63,<0.6.0
    - numpy >=2.0.0,<3.0.0
    - scipy >=1.13.0,<2.0.0
    - psutil >=6.0.0,<7.0.0

test:
  imports:
    - sober

about:
  home: https://github.com/airallergy/sober
  summary: sober optimises built environment robustly
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - airallergy
