schema_version: 1

context:
  name: sober
  python_min: "3.12"
  version: "0.4.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: cf25a7f30472f02c6b6c2d30950a0baa9f1084dbbb867b6d774a40236ea55737

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - eppy-core >=0.5.63,<0.6.0
    - numpy >=2.3,<3.0
    - psutil >=7,<8
    - pymoo >=0.6.1,<0.7.0
    - scipy >=1.17,<2.0

tests:
  - python:
      imports:
        - sober
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  summary: sober optimises built environment robustly
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/airallergy/sober # make conda-forge-linter happy, not defined in upstream
  repository: https://github.com/airallergy/sober
  documentation: https://airallergy.github.io/sober

extra:
  recipe-maintainers:
    - airallergy
